import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Generated by `supabase start`/`supabase db reset` (local Docker
      // dev stack) - gitignored, but ESLint's flat config doesn't read
      // .gitignore on its own, so anyone who runs the local stack was
      // getting lint errors from a bundled edge-runtime file in here.
      "supabase/.temp/**",
      "supabase/.branches/**",
    ],
  },
  {
    rules: {
      // The codebase already names an intentionally-unused parameter
      // with a leading underscore (e.g. getFacilitator's _cohortId - no
      // facilitator display name/bio exists in the schema yet, kept for
      // future use and so callers don't need to change when it's built)
      // - this was silently NOT honored by next/typescript's default
      // preset, producing warnings on a pattern the codebase already
      // uses as its own "deliberately unused" convention.
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
];

export default eslintConfig;
