import { describe, expect, it, vi, beforeAll, afterAll } from "vitest";
import { createAdminClient } from "@/lib/supabase/admin";
import { ForbiddenError } from "@/lib/auth/roles";
import { clientForUser } from "@/test/helpers/local-auth";
import {
  listPendingReviewApplicants,
  listDeclinedApplicants,
  declineApplicantAction,
  reopenApplicantAction,
} from "@/lib/admin/applicants";

// revalidatePath only works inside a real Next.js request - outside it
// (calling the action directly, as this suite does) it throws its own
// "static generation store missing" invariant. Same reasoning as
// lib/admin/partner-organizations.test.ts.
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));

const admin = createAdminClient();

describe("applicant review queue", () => {
  let adminUser: { id: string };
  let memberUser: { id: string };
  let partnerOrgId: string;
  // Generated by Postgres and captured below, not hardcoded - every
  // other suite in this codebase Date.now()-suffixes its identifiers for
  // exactly this reason (repeated/concurrent local runs must never
  // collide on a fixed id), and a hardcoded applicant id here shipped a
  // real flaky-test bug the first time this file ran as part of the
  // full suite instead of alone.
  let pendingId: string;
  let olderPendingId: string;

  beforeAll(async () => {
    const { data: adminData, error: adminError } = await admin.auth.admin.createUser({
      email: `applicants-admin-${Date.now()}@example.com`,
      email_confirm: true,
    });
    if (adminError || !adminData.user) throw adminError ?? new Error("createUser failed");
    adminUser = adminData.user;
    await admin.from("profiles").update({ role: "admin" }).eq("id", adminUser.id);

    const { data: memberData, error: memberError } = await admin.auth.admin.createUser({
      email: `applicants-member-${Date.now()}@example.com`,
      email_confirm: true,
    });
    if (memberError || !memberData.user) throw memberError ?? new Error("createUser failed");
    memberUser = memberData.user;

    const { data: org, error: orgError } = await admin
      .from("partner_organizations")
      .insert({ name: "Applicants Test Org", referral_link_slug: `applicants-test-org-${Date.now()}` })
      .select("id")
      .single();
    if (orgError || !org) throw orgError ?? new Error("failed to create partner org");
    partnerOrgId = org.id;

    // Older first - backdated via a follow-up UPDATE, not the insert
    // itself: the applicants_stamp_pending_review_since trigger
    // unconditionally stamps pending_review_since to now() on any INSERT
    // landing in pending_review, so an explicit value in the insert
    // itself would just get overwritten. A separate UPDATE that leaves
    // status unchanged doesn't retrigger that stamp (its condition
    // requires either an INSERT or an actual status change).
    const oldTimestamp = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString();
    const { data: olderRow, error: olderError } = await admin
      .from("applicants")
      .insert({
        partner_organization_id: partnerOrgId,
        referral_source: "partner_link",
        first_name: "Older",
        last_name: "Applicant",
        status: "pending_review",
      })
      .select("id")
      .single();
    if (olderError || !olderRow) throw olderError ?? new Error("failed to create older applicant");
    olderPendingId = olderRow.id;
    await admin.from("applicants").update({ pending_review_since: oldTimestamp }).eq("id", olderPendingId);

    const { data: newerRow, error: newerError } = await admin
      .from("applicants")
      .insert({
        partner_organization_id: partnerOrgId,
        referral_source: "staff_form",
        first_name: "Newer",
        last_name: "Applicant",
        status: "pending_review",
      })
      .select("id")
      .single();
    if (newerError || !newerRow) throw newerError ?? new Error("failed to create newer applicant");
    pendingId = newerRow.id;
  });

  afterAll(async () => {
    await admin.from("applicants").delete().in("id", [pendingId, olderPendingId]);
    await admin.from("partner_organizations").delete().eq("id", partnerOrgId);
    await admin.auth.admin.deleteUser(memberUser.id);
    await admin.auth.admin.deleteUser(adminUser.id);
  });

  it("rejects a non-admin caller for every export", async () => {
    const memberClient = await clientForUser(memberUser.id);
    await expect(listPendingReviewApplicants(memberClient)).rejects.toThrow(ForbiddenError);
    await expect(listDeclinedApplicants(memberClient)).rejects.toThrow(ForbiddenError);
    await expect(declineApplicantAction(pendingId, "other", memberClient)).rejects.toThrow(ForbiddenError);
    await expect(reopenApplicantAction(pendingId, memberClient)).rejects.toThrow(ForbiddenError);
  });

  it("lists pending_review applicants oldest first, with days waiting computed", async () => {
    const adminClient = await clientForUser(adminUser.id);
    const queue = await listPendingReviewApplicants(adminClient);
    const ids = queue.map((a) => a.id);

    expect(ids.indexOf(olderPendingId)).toBeLessThan(ids.indexOf(pendingId));

    const older = queue.find((a) => a.id === olderPendingId)!;
    expect(older.daysWaiting).toBeGreaterThanOrEqual(5);

    const newer = queue.find((a) => a.id === pendingId)!;
    expect(newer.daysWaiting).toBe(0);
  });

  it("declining moves an applicant out of the pending queue and into declined", async () => {
    const adminClient = await clientForUser(adminUser.id);

    const result = await declineApplicantAction(pendingId, "not_a_fit", adminClient);
    expect(result).toEqual({ success: true });

    const pending = await listPendingReviewApplicants(adminClient);
    expect(pending.some((a) => a.id === pendingId)).toBe(false);

    const declined = await listDeclinedApplicants(adminClient);
    const declinedRow = declined.find((a) => a.id === pendingId);
    expect(declinedRow?.declineReason).toBe("not_a_fit");
  });

  it("reopening returns a declined applicant to the pending queue", async () => {
    const adminClient = await clientForUser(adminUser.id);

    const result = await reopenApplicantAction(pendingId, adminClient);
    expect(result).toEqual({ success: true });

    const pending = await listPendingReviewApplicants(adminClient);
    expect(pending.some((a) => a.id === pendingId)).toBe(true);

    const declined = await listDeclinedApplicants(adminClient);
    expect(declined.some((a) => a.id === pendingId)).toBe(false);
  });

  it("declining an applicant who is not pending_review fails gracefully instead of throwing", async () => {
    const adminClient = await clientForUser(adminUser.id);

    // pendingId is back in pending_review after the reopen test above;
    // decline it once more, then try declining it a second time.
    await declineApplicantAction(pendingId, "other", adminClient);
    const result = await declineApplicantAction(pendingId, "other", adminClient);
    expect(result).toEqual({ success: false, error: expect.any(String) });
  });
});
